spring:
  h2.console:
    enabled: true
    path: '/console'
    main:
      banner-mode: off
datasource:
  url: 'jdbc:h2:file:/home/mateusz/Desktop/app/todo-app/db'
task.allowMultipleTasksFromTemplate: false